function y = doFilter_theta(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 02-Apr-2023 04:58:06

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 8;     % Order
    % F3dB = 40.4;  % 3-dB Frequency
    % Fs   = 112;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.11479888110449 0.739493369349116; 1 2 1 1 ...
        0.898540966749235 0.40205204745118; 1 2 1 1 0.782379379436961 ...
        0.220797550045715; 1 2 1 1 0.731219767972008 0.140969873116588], ...
        'ScaleValues', [0.713573062613402; 0.575148253550104; ...
        0.500794232370669; 0.468047410272149; 1]);
end

s = double(x);
y = step(Hd,s);

