function y = doFilter_human_dyaw(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jun-2023 04:09:04

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 9;     % Order
    % F3dB = 37.7;  % 3-dB Frequency
    % Fs   = 100;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.27704965597295 0.783747142739207; 1 2 1 1 ...
        1.06136781382204 0.482488794735263; 1 2 1 1 0.932922174226046 ...
        0.303079527793247; 1 2 1 1 0.864625795275638 0.207685061147069; 1 1 0 1 ...
        0.42159407735801 0], ...
        'ScaleValues', [0.765199199678039; 0.635964152139325; ...
        0.559000425504823; 0.518077714105677; 0.710797038679005; 1]);
end

s = double(x);
y = step(Hd,s);

