function y = doFilter_human_ddyaw(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jun-2023 03:00:07

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 8;     % Order
    % F3dB = 36.8;  % 3-dB Frequency
    % Fs   = 100;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.18077389456214 0.74843259554856; 1 2 1 1 ...
        0.958095319556821 0.418700984219211; 1 2 1 1 0.837248378464117 ...
        0.239756707205725; 1 2 1 1 0.783747862415505 0.160535743252461], ...
        'ScaleValues', [0.732301622527675; 0.594199075944008; ...
        0.519251271417461; 0.486070901416992; 1]);
end

s = double(x);
y = step(Hd,s);

