function y = doFilter_human_roll(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jun-2023 06:02:43

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 9;     % Order
    % Fpass = 34.8;  % Passband Frequency
    % Apass = 5;     % Passband Ripple (dB)
    % Astop = 55;    % Stopband Attenuation (dB)
    % Fs    = 100;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,fp,ap,ast', N, Fpass, Apass, Astop, Fs);
    %
    % Hd = design(h, 'ellip', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 1.18271502108232 1 1 1.15105687147505 ...
        0.997016259400828; 1 1.21389863254335 1 1 1.11247011808713 ...
        0.984664118125035; 1 1.33259569698721 1 1 0.951677397547669 ...
        0.938232136949667; 1 1.66796115963113 1 1 0.274372118684784 ...
        0.743971742357934; 1 1 0 1 -0.577885285793815 0], ...
        'ScaleValues', [0.136925211075329; 0.96366892373367; ...
        0.867164756021837; 0.550263149800009; 1.52462885608715; 1]);
end

s = double(x);
y = step(Hd,s);

