function y = doFilter_human_dpitch(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jun-2023 00:32:16

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 7;     % Order
    % F3dB = 36.5;  % 3-dB Frequency
    % Fs   = 100;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.13343581955972 0.71392028329177; 1 2 1 1 ...
        0.901162229515777 0.362688735479955; 1 2 1 1 0.78923656838188 ...
        0.193440810253149; 1 1 0 1 0.377868511775821 0], ...
        'ScaleValues', [0.711839025712873; 0.565962741248933; ...
        0.495669344658757; 0.68893425588791; 1]);
end

s = double(x);
y = step(Hd,s);

