function y = doFilter_human_droll(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 06-Jun-2023 21:05:59

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 8;    % Order
    % F3dB = 35;   % 3-dB Frequency
    % Fs   = 100;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.01532098615661 0.727367235221825; 1 2 1 1 ...
        0.811037098605681 0.379818727064831; 1 2 1 1 0.702809498205855 ...
        0.195690935532604; 1 2 1 1 0.655471917606866 0.115155433128685], ...
        'ScaleValues', [0.685672055344609; 0.547713956417628; ...
        0.474625108434615; 0.442656837683888; 1]);
end

s = double(x);
y = step(Hd,s);

