function y = doFilter_human_ddpitch(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Jun-2023 03:10:54

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 8;    % Order
    % F3dB = 36;   % 3-dB Frequency
    % Fs   = 100;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.10825538793627 0.738647126182387; 1 2 1 1 ...
        0.892704286658495 0.400487432251258; 1 2 1 1 0.77703440307258 ...
        0.219022841262898; 1 2 1 1 0.726116156823418 0.139141558054155], ...
        'ScaleValues', [0.711725628529664; 0.573297929727438; ...
        0.499014311083869; 0.466314428719393; 1]);
end

s = double(x);
y = step(Hd,s);

