function y = doFilter_human_py(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 06-Jun-2023 21:32:47

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 8;     % Order
    % F3dB = 39.8;  % 3-dB Frequency
    % Fs   = 100;   % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 1.43566960566949 0.791078765426899; 1 2 1 1 ...
        1.20339302714323 0.501300639692748; 1 2 1 1 1.07079775953701 ...
        0.335880568620853; 1 2 1 1 1.01053794149575 0.260703048614874], ...
        'ScaleValues', [0.806687092774098; 0.676173416708995; ...
        0.601669582039465; 0.567810247527655; 1]);
end

s = double(x);
y = step(Hd,s);

